---

- name: Install software
  hosts: all
  tasks:
    - name: Install rsync
      apt:
        name: rsync
        state: present
      become: true

- name: Install docker
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker
    pip_package: python3-pip
    docker_users:
      - "{{ user }}"

  roles:
    - geerlingguy.pip
    - geerlingguy.docker